spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacoclouddb
    username: root
    password: root
  jpa :
    hibernate :
      ddl-auto: create

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
          show-details: always

info:
  contact:
    email: support@tacocloud.com
    phone: 822-625-6831
