spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:tacoclouddb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2